title: Your Website Title
remote_theme: alshedivat/al-folio
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-scholar
