name: Deploy site

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Ruby 💎
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4  # ❗降级为 al-folio 支持的版本
          bundler-cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libvips libmagickwand-dev
          bundle install

      - name: Build site with Jekyll 🔧
        run: |
          bundle exec jekyll build

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site
